### ISSUE TITLE
demo @ http://54.183.244.111:8000 down?

### ISSUE THREAD

**Issue by evandrix** [suggest-go/suggest#32]

**Comment by alldroll** [comment]
Thanks, you are right. The free trial aws period has ended :( I will fix it soon ...

If you would like to see how it works, you can do the next:

* clone project
* make build
* ./build/suggest eval -c pkg/suggest/testdata/config.json -d words -s 0.5 -k 5 

You will have fuzzy string search access to a word dictionary with more than 200k words

**Comment by alldroll** [comment]
As a compromise, I added a gif demo and the description of how to run it manually #33

**Comment by evandrix** [comment]
:+1:

**Comment by alldroll** [comment]
@evandrix I have created documentation page with demos

https://suggest-go.github.io/docs/demo.html
https://suggest-go.github.io/docs/purpose.html
